parameters:
#    basto_front_end.example.class: Basto\FrontEndBundle\Example

services:
#    basto_front_end.example:
#        class: %basto_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
