<?php

namespace Basto\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TercerosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CopiasRepository extends EntityRepository
{   
    
}